name: Package and release on Github

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Building Ghostferry
        run: .github/workflows/build-deb.sh

      - name: Releasing Ghostferry to Github
        run: gh release create --target ${GITHUB_REF#refs/heads/} -p release-${GITHUB_SHA::7} build/ghostferry*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
